### ISSUE TITLE
Connection troubles or standards change

### ISSUE THREAD

**Issue by duayres** [cooperaj/wow-armory-character#27]
Look at the example page (http://realmenweardress.es/about/) and you will see the error
"Unable to fetch data from battle.net for character " ... anything happened to wowhead markup language?!

**Comment by cooperaj** [comment]
Not sure what caused this. I refreshed a few times and it came up as normal. I could be an issue but is likely connection or armoury issues. Sadly I can't do much about those.

**Comment by duayres** [comment]
I've tried here the same URL I wrote in the main issue again, yet "unable to fetch data from battle.net from character", Cache cleared, nothing too.
